services:
  dataset-service-db:
    image: postgres:16-alpine
    container_name: dataset-service-db
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORDWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataset_user -d dataset_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tpp-network

  dataset-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataset-service
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    depends_on:
      dataset-service-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - tpp-network

volumes:
  postgres_data:

networks:
  tpp-network:
    external: true
