services:
  proto-gen:
    build:
      context: .
      dockerfile: Dockerfile.proto
    volumes:
      - ./src/pb:/app/out

  dataset-grpc-service:
    build: .
    container_name: dataset-grpc-service
    ports:
      - "50051:50051"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - proto-gen
    volumes:
      - ./src/pb:/app/src/pb
    restart: unless-stopped